name: Update Playlist

on:
  schedule:
    - cron: '*/30 * * * *' # Runs automatically every 30 minutes
  workflow_dispatch: # Allows you to press the button to run manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Script Extraction
        run: python convert.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add live_sports.m3u
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated playlist update" && git push)
